### ISSUE TITLE
Heroku Deploy Failure

### ISSUE THREAD

**Issue by sethazazel** [patheticGeek/torrent-aio-bot#1]
Heroku deployment failed.
[https://del.dog/sesitytybo.txt](https://del.dog/sesitytybo.txt)

**Comment by patheticGeek** [comment]
Add a buildpack from settings > buildpacks > add buildpacks
"https://github.com/jontewks/puppeteer-heroku-buildpack.git"
then redploy from heroku cli. For some reason heroku doesnt detect this buildpack in app.json so it doesnt add it automatically
