### ISSUE TITLE
Guide for VPS

### ISSUE THREAD

**Issue by rockydares** [patheticGeek/torrent-aio-bot#106]
I want to run on my vps, brief guidance please

**Comment by patheticGeek** [comment]
Use these commands

```sh
git clone https://github.com/patheticGeek/torrent-aio-bot/ # clone the repo
cd torrent-aio-bot 
nano .env # set your env variables
npm start # start the bot
```

I would recommend running it with PM2 but you are free to use whatever to manage it
Also you might need to map your ports check your VPS's guide on that

**Comment by rockydares** [comment]
> Use these commands
> 
> ```shell
> git clone https://github.com/patheticGeek/torrent-aio-bot/ # clone the repo
> cd torrent-aio-bot 
> nano .env # set your env variables
> npm start # start the bot
> ```
> 
> I would recommend running it with PM2 but you are free to use whatever to manage it
> Also you might need to map your ports check your VPS's guide on that

It was too brief. Anyway I tried this
cd torrent-aio-bot
npm install
cd web && npm install && npm run build
npm start

And the website got running on 3000 port. 

Will you please write down .env example where I can change port, give Drive auth and folder details.
I tried with PORT=80 but didn't work.

**Comment by rockydares** [comment]
I can give you one vps if you wanna try this on a vps. I am currently running another python based torrent web app which has most of functions but that is too unstable.

**Comment by patheticGeek** [comment]
In the docs whatever you set in heroku's setting is all env variables. just take the name then out = and then value. create a file names `.env` in root of project and put your variables in there
example of env file:
```
PORT=8080
CLIENT_ID=hdhakavdghsj
CLIENT_SECRET=hdhhakakbsgh
```
Read the env for all options.
