### ISSUE TITLE
how to set configs

### ISSUE THREAD

**Issue by gbisheraz581m** [patheticGeek/torrent-aio-bot#12]
Hello,how do you set configs for your heroku app after deploying it?I really am a noob when it comes to programming,could someone please help me out?

**Comment by patheticGeek** [comment]
Goto the settings panel in heroku there you will see Reveal config vars button, those are the config vars.
![congif vars](https://user-images.githubusercontent.com/11344611/81962705-b9068e80-9631-11ea-8f45-19d007734201.png)

**Comment by patheticGeek** [comment]
I'm closing this issue please feel free to reopen if you have any other problems
