### ISSUE TITLE
Add support for GDRIVE TEAM DRIVES

### ISSUE THREAD

**Issue by telegrambotdev** [patheticGeek/torrent-aio-bot#13]
Kindly add support for gdrive shared drives too.alot of peopes are using shared drives for unlimited storage

**Comment by patheticGeek** [comment]
Im a nOOb. This feature is last of the list becuase i want to address some other things first

**Comment by telegrambotdev** [comment]
haha ok bro thanks.but dont forget about that

**Comment by patheticGeek** [comment]
Teamdrive support added read docs
