### ISSUE TITLE
How to get AUTH_CODE

### ISSUE THREAD

**Issue by samarth1220** [patheticGeek/torrent-aio-bot#14]
I did not understand how to restart the process 2 times and how to get the AUTH_CODE.
Please explain in detail.

**Comment by patheticGeek** [comment]
When you add an env var the server is restarted automatically for change to take effect that is what im refering to. So when you add the vars go to logs and when it is restarted it will authenticate with google auth and give a token

**Comment by patheticGeek** [comment]
Please feel free to reopen this issue if you havent fixed it yet, read docs as i updated and made it easy
