### ISSUE TITLE
Cannot connect to site ( after torrent search)

### ISSUE THREAD

**Issue by ccharya** [patheticGeek/torrent-aio-bot#16]
![Screenshot_20200523-141027__01](https://user-images.githubusercontent.com/52544823/82726109-a65e1a80-9cff-11ea-9ad5-36992e3be9b8.jpg)

I can search but can't load it , I'm using "SEARCH_SITE = https://torrent-aio-bot.herokuapp.com/"

**Comment by patheticGeek** [comment]
Its' a known problem i will fix it today

**Comment by patheticGeek** [comment]
Just made a fix try updating your fork

**Comment by ccharya** [comment]
Search is working , but can't add torrents with download button ... Have to copy and then paste it in download section ... But it's fine . Thanks for the solution ❤️💋

**Comment by patheticGeek** [comment]
Just made a fix try updating your fork
