### ISSUE TITLE
After Downloading the torrent is not getting uploaded to G-drive

### ISSUE THREAD

**Issue by Nenokkadine** [patheticGeek/torrent-aio-bot#21]

**Comment by Nenokkadine** [comment]
it is showing an error
![Screenshot (17)](https://user-images.githubusercontent.com/65813999/83223502-954a5900-a198-11ea-9709-35a6e3d2f3ad.png)

**Comment by patheticGeek** [comment]
Can you provide logs from heroku?

**Comment by Nenokkadine** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/65813999/83238270-d0a65100-a1b3-11ea-8f8c-ab625d8895a4.png)
![Screenshot (18)](https://user-images.githubusercontent.com/65813999/83238272-d308ab00-a1b3-11ea-9c7c-5465854aee70.png)

**Comment by patheticGeek** [comment]
Add the torrent and when it fails those error logs i mean

**Comment by Nenokkadine** [comment]
[jeffbezos-logs-1590744468657.txt](https://github.com/patheticGeek/torrent-aio-bot/files/4700882/jeffbezos-logs-1590744468657.txt)
I Downloaded the log file after my torrents have downloaded but got automatically deleted

**Comment by patheticGeek** [comment]
Okay i know what caused this thanks for reporting will look into it tonight

**Comment by patheticGeek** [comment]
This problem is fixed kindly updtae your deployment
