### ISSUE TITLE
Search is dead again 

### ISSUE THREAD

**Issue by ccharya** [patheticGeek/torrent-aio-bot#22]
search is dead (loading...) like before , im using SEARCH_SITE - https://torrent-aio-bot.herokuapp.com/ 
i checked your site , search is dead on your site so its not working for us 2.

**Comment by patheticGeek** [comment]
It is because the website the bot scrapps like 1337x.to might be down. to change the website set search site to your own site and look in https://github.com/patheticGeek/torrent-aio-bot#changing-the-sites-used-for-searching here

**Comment by patheticGeek** [comment]
Its back up i just fixed it update your deployment
