### ISSUE TITLE
how to use it in telegram and linking it to commands

### ISSUE THREAD

**Issue by sam23-dot** [patheticGeek/torrent-aio-bot#23]

**Comment by sam23-dot** [comment]
actually only bot token been keyed here but no other cahnges for command (related) been done

**Comment by patheticGeek** [comment]
> actually only bot token been keyed here but no other changes for command (related) been done

What commands do you want can you explain?

**Comment by dstar22** [comment]
how to configure commands in bot means ?  what i did was go to bot father and used /setcommands 
after that what we have to do like /torrent/download - download ?  how to configure please help

**Comment by patheticGeek** [comment]
Its not necessary, just send the bot `/start` it will list all the commands. setting commands there is just for that window to pop up not for the commands to work. commands still work

**Comment by dstar22** [comment]
> Its not necessary, just send the bot `/start` it will list all the commands. setting commands there is just for that window to pop up not for the commands to work. commands still work

Nothing happens when i send /start what am i doing wrong?
