### ISSUE TITLE
 "SET SITE ENVIORMENT VARIABLE" error

### ISSUE THREAD

**Issue by todokku** [patheticGeek/torrent-aio-bot#3]
after complete torrent magnet leech & using comment /torrent download "startedcompletemagnet" getting error like bellow 

`Name: evilangel.20.01.27.gabbie.carter.gabbies.pussy.eaten.and.fucked.mp4

Download Link: 
 SET SITE ENVIORMENT VARIABLE. READ DOCSapi/v1/downloads/b54720a505d5f8d23cd918b2f407e7e3cb3ff92d/EvilAngel.20.01.27.Gabbie.Carter.Gabbies.Pussy.Eaten.And.Fucked..480p.MP4-XXX/evilangel.20.01.27.gabbie.carter.gabbies.pussy.eaten.and.fucked.mp4`

**Comment by patheticGeek** [comment]
read the readme.md file .. go to settings > environment variables > reveal config vars
and set a variable with key "SITE" and value a link to your homepage like https://<project-name>.herokuapp.com/    remember to add a tralling / in the end
