### ISSUE TITLE
[Feature Request] Archive

### ISSUE THREAD

**Issue by sethazazel** [patheticGeek/torrent-aio-bot#4]
Can you add an option for archiving (zip/tar) folder after download complete. It will be handy especially when you download a torrent that have too much small files.

**Comment by patheticGeek** [comment]
Will come till the end of month i am hoping to instead add a gdrive acc to upload on it and give that link

**Comment by patheticGeek** [comment]
Fuctionality added.
It saves the zip file in the downloads/${torrent.infoHash} folder
