### ISSUE TITLE
I can't setup download

### ISSUE THREAD

**Issue by mrsajib121** [patheticGeek/torrent-aio-bot#41]
I can't setup variable key plesee help me ;(

**Comment by patheticGeek** [comment]
Whats the error?

**Comment by mrsajib121** [comment]
Actually i'm noob on github. 
But when i upload torrent my site after upload finish i can't find my file and show some error like this https://torbdz.herokuapp.com/SET%20SITE%20ENVIORMENT%20VARIABLE.%20READ%20DOCSdownloads/9d06756ac32350249af576dc147f6f61e1755a66
Please help me out fix this issue.
Sorry for bad english ;(
