### ISSUE TITLE
problem on piratebay searches

### ISSUE THREAD

**Issue by todokku** [patheticGeek/torrent-aio-bot#5]
Hi ,
on all piratebay only searches received : "No results found"
https://torgetbot.herokuapp.com
please check it
waiting for your response
finest regards

**Comment by patheticGeek** [comment]
This happens beacuse the site/proxy the bot uses is not available
deployed a dirty fix, will be adding functionality so that site can be changed using an enviorment variable

**Comment by nexusdiscord** [comment]
crawler not working because piratebay has tableless now
