### ISSUE TITLE
Slow download speed?

### ISSUE THREAD

**Issue by razerblade1211** [patheticGeek/torrent-aio-bot#53]
Hi,
My download speed is very slow when I try to download on my PC. The torrent working well.
![image](https://user-images.githubusercontent.com/44914014/89303914-032e6780-d697-11ea-8270-6abf7f8e3783.png)

**Comment by patheticGeek** [comment]
It is due to limitations of web-torrent library i'm using unfortunately this is the best i am able to make it work on heroku without getting banned. Some torrents are fast af some don't even start
