### ISSUE TITLE
APP in Heroku Sleep 

### ISSUE THREAD

**Issue by NEOIR** [patheticGeek/torrent-aio-bot#57]
Hi  

1. After one Day Deployment in Heroku APP Sleep and Web Version isnt Working But bot Work Properly.

![image](https://user-images.githubusercontent.com/53754407/91544602-316d3300-e935-11ea-89ef-6c090547d239.png)

![image](https://user-images.githubusercontent.com/53754407/91544145-91afa500-e934-11ea-84e8-2728db80b186.png)

2. How to See and Manage Downloaded Files in Heroku Store for Managing and Deleting After UPloaded to GDrive

Thanks For This Repo

**Comment by patheticGeek** [comment]
Looks like you're typing the url wrong for heroku
Heroku files are there till the app sleeps. will add new features next month
