### ISSUE TITLE
Empty Folders at https://<project name>.herokuapp.com/downloads/ after torrent completes

### ISSUE THREAD

**Issue by magarkancha** [patheticGeek/torrent-aio-bot#86]
As title says empty folder with torrents folder name, i have attached logs after adding magnet link
to reproduce bug you have to change Config variables by https:..../drivehelp  or create new deploy
I think others having bug not uploading to g-drive is same as there is no files on herokuapp
[logs.txt](https://github.com/patheticGeek/torrent-aio-bot/files/5977070/morning-oasis-69233-logs.txt)

**Comment by please2k** [comment]
Same Problem. Hosted on Heroku yesterday.
