### ISSUE TITLE
Upload files to OneDrive

### ISSUE THREAD

**Issue by sobuj53** [patheticGeek/torrent-aio-bot#93]
Hello,
I've OneDrive Business. Is it possible to upload downloaded files in there instead of Gdrive? If so would you please tell us how?

Would really appreciate your response on this thanks.

**Comment by mau551** [comment]
let me tell you that it is not simple, microsoft is much more complicated than google, but I found this that might work: https://github.com/gautamajay52/TorrentLeech-Gdrive (I have not tested it so I can't assure you anything), I remember that once I found one that allowed uploading to OneDrive but I don't remember which one it was. although this one does not give official support for heroku, here is a fork that does (although it is far behind the original branch): https://github.com/MaxxRider/Max-Torrent-Leech-V2

**Comment by sobuj53** [comment]
I've a colab notebook that helps me to upload downloaded torrent to OneDrive business directly but the speed of transfer is very poor. For now I'll stick with Gdrive, but someday and that day may never come when Gdrive will become more strict then we'll have to look for alternatives.

**Comment by sobuj53** [comment]
> let me tell you that it is not simple, microsoft is much more complicated than google, but I found this that might work: https://github.com/gautamajay52/TorrentLeech-Gdrive (I have not tested it so I can't assure you anything), I remember that once I found one that allowed uploading to OneDrive but I don't remember which one it was. although this one does not give official support for heroku, here is a fork that does (although it is far behind the original branch): https://github.com/MaxxRider/Max-Torrent-Leech-V2

I never really thanked you for your valuable comments. After a very long time because of you I got what I wanted. Thank you man.
